/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpu;

import java.awt.Color;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author Renan
 */
public class GUI extends javax.swing.JFrame {
    
    
    //Highlight
    Highlighter highlighter;
    Highlighter.HighlightPainter painter;
    
    //fim do programa
    boolean ultimaInstrucao = false;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        CodigoText.setText(Main.Code);
        
        //Highlight
        this.highlighter = CodigoText.getHighlighter();
        this.painter = new DefaultHighlighter.DefaultHighlightPainter(Color.pink);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrincipalPanel = new javax.swing.JPanel();
        MicroprogramaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        palavra = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        DescricaoPane = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        RegistradoresPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dx = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mbr = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ir = new javax.swing.JTextField();
        FlagsPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        overflow = new javax.swing.JTextField();
        sinal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        zero = new javax.swing.JTextField();
        BarramentosPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        barramentoInterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        barramentoExterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CodigoPane = new javax.swing.JScrollPane();
        CodigoText = new javax.swing.JTextArea();
        Step = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        clock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MicroprogramaPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Microprograma");

        jLabel18.setText("Palavra");

        palavra.setEditable(false);
        palavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palavraActionPerformed(evt);
            }
        });

        jLabel19.setText("Descrição");

        descricao.setEditable(false);
        descricao.setColumns(20);
        descricao.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        descricao.setRows(3);
        DescricaoPane.setViewportView(descricao);

        javax.swing.GroupLayout MicroprogramaPanelLayout = new javax.swing.GroupLayout(MicroprogramaPanel);
        MicroprogramaPanel.setLayout(MicroprogramaPanelLayout);
        MicroprogramaPanelLayout.setHorizontalGroup(
            MicroprogramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MicroprogramaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MicroprogramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MicroprogramaPanelLayout.createSequentialGroup()
                        .addGroup(MicroprogramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MicroprogramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palavra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DescricaoPane))))
                .addContainerGap())
        );
        MicroprogramaPanelLayout.setVerticalGroup(
            MicroprogramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MicroprogramaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(MicroprogramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MicroprogramaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescricaoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        RegistradoresPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Registradores");

        ax.setEditable(false);

        jLabel6.setText("AX");
        jLabel6.setMaximumSize(new java.awt.Dimension(28, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(28, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(28, 14));

        jLabel7.setText("BX");
        jLabel7.setMaximumSize(new java.awt.Dimension(28, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(28, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(28, 14));

        bx.setEditable(false);

        jLabel8.setText("CX");
        jLabel8.setMaximumSize(new java.awt.Dimension(28, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(28, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(28, 14));

        cx.setEditable(false);

        jLabel9.setText("DX");
        jLabel9.setMaximumSize(new java.awt.Dimension(28, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(28, 14));
        jLabel9.setPreferredSize(new java.awt.Dimension(28, 14));

        dx.setEditable(false);

        jLabel10.setText("PC");
        jLabel10.setMaximumSize(new java.awt.Dimension(28, 14));
        jLabel10.setMinimumSize(new java.awt.Dimension(28, 14));
        jLabel10.setPreferredSize(new java.awt.Dimension(28, 14));

        pc.setEditable(false);

        jLabel11.setText("MAR");
        jLabel11.setMaximumSize(new java.awt.Dimension(28, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(28, 14));
        jLabel11.setPreferredSize(new java.awt.Dimension(28, 14));

        mar.setEditable(false);

        jLabel12.setText("MBR");
        jLabel12.setMaximumSize(new java.awt.Dimension(28, 14));
        jLabel12.setMinimumSize(new java.awt.Dimension(28, 14));
        jLabel12.setPreferredSize(new java.awt.Dimension(28, 14));

        mbr.setEditable(false);

        jLabel13.setText("IR");
        jLabel13.setMaximumSize(new java.awt.Dimension(28, 14));
        jLabel13.setMinimumSize(new java.awt.Dimension(28, 14));
        jLabel13.setPreferredSize(new java.awt.Dimension(28, 14));

        ir.setEditable(false);

        FlagsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Flags");

        jLabel17.setText("Overflow");
        jLabel17.setMaximumSize(new java.awt.Dimension(70, 14));
        jLabel17.setMinimumSize(new java.awt.Dimension(70, 14));
        jLabel17.setPreferredSize(new java.awt.Dimension(70, 14));

        overflow.setEditable(false);

        sinal.setEditable(false);

        jLabel16.setText("Sinal");

        jLabel20.setText("Zero");

        zero.setEditable(false);
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FlagsPanelLayout = new javax.swing.GroupLayout(FlagsPanel);
        FlagsPanel.setLayout(FlagsPanelLayout);
        FlagsPanelLayout.setHorizontalGroup(
            FlagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlagsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FlagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FlagsPanelLayout.createSequentialGroup()
                        .addGroup(FlagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(sinal)
                            .addComponent(overflow)))
                    .addComponent(jLabel14))
                .addContainerGap())
        );
        FlagsPanelLayout.setVerticalGroup(
            FlagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlagsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FlagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FlagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FlagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overflow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegistradoresPanelLayout = new javax.swing.GroupLayout(RegistradoresPanel);
        RegistradoresPanel.setLayout(RegistradoresPanelLayout);
        RegistradoresPanelLayout.setHorizontalGroup(
            RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistradoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(RegistradoresPanelLayout.createSequentialGroup()
                        .addGroup(RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistradoresPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bx, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistradoresPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cx, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mbr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistradoresPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dx, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistradoresPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(FlagsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        RegistradoresPanelLayout.setVerticalGroup(
            RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistradoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistradoresPanelLayout.createSequentialGroup()
                        .addGroup(RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistradoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(FlagsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BarramentosPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Barramentos");

        barramentoInterno.setEditable(false);

        jLabel3.setText("Interno");

        barramentoExterno.setEditable(false);

        jLabel4.setText("Externo");

        javax.swing.GroupLayout BarramentosPanelLayout = new javax.swing.GroupLayout(BarramentosPanel);
        BarramentosPanel.setLayout(BarramentosPanelLayout);
        BarramentosPanelLayout.setHorizontalGroup(
            BarramentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarramentosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarramentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BarramentosPanelLayout.createSequentialGroup()
                        .addGroup(BarramentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BarramentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barramentoInterno)
                            .addComponent(barramentoExterno))))
                .addContainerGap())
        );
        BarramentosPanelLayout.setVerticalGroup(
            BarramentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarramentosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BarramentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barramentoInterno)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BarramentosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barramentoExterno)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CodigoText.setEditable(false);
        CodigoText.setColumns(20);
        CodigoText.setRows(5);
        CodigoPane.setViewportView(CodigoText);

        Step.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Step.setText("STEP");
        Step.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Clock");

        clock.setEditable(false);
        clock.setText("0");
        clock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrincipalPanelLayout = new javax.swing.GroupLayout(PrincipalPanel);
        PrincipalPanel.setLayout(PrincipalPanelLayout);
        PrincipalPanelLayout.setHorizontalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CodigoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MicroprogramaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PrincipalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clock, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(260, 260, 260)
                        .addComponent(Step))
                    .addComponent(BarramentosPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistradoresPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PrincipalPanelLayout.setVerticalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrincipalPanelLayout.createSequentialGroup()
                        .addComponent(MicroprogramaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegistradoresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BarramentosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Step)))
                    .addComponent(CodigoPane))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void palavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palavraActionPerformed
        // TODadd your handling code here:
    }//GEN-LAST:event_palavraActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zeroActionPerformed

    private void StepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepActionPerformed
        
        UC.step();
        
        //Atualização das caixas de texto
        ax.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(AX.get(),2))).replace(' ', '0'));
        bx.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(BX.get(),2))).replace(' ', '0'));
        cx.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(CX.get(),2))).replace(' ', '0'));
        dx.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(DX.get(),2))).replace(' ', '0'));
        pc.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(PC.get(),2))).replace(' ', '0'));
        mar.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(MAR.get(),2))).replace(' ', '0'));
        mbr.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(MBR.get(),2))).replace(' ', '0'));
        ir.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(IR.get(),2))).replace(' ', '0'));
        zero.setText(UC.getZero() ? "1" : "0");
        sinal.setText(UC.getSinal() ? "1" : "0");
        overflow.setText(UC.getOverflow() ? "1" : "0");
        barramentoInterno.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(Barramentos.getInterno(),2))).replace(' ', '0'));
        barramentoExterno.setText(String.format("%4s",Integer.toHexString(Integer.parseInt(Barramentos.getExterno(),2))).replace(' ', '0'));
        palavra.setText(UC.getCBR().equals("0") ? "00000000000000000000000000000000000" : UC.getCBR());
        descricao.setText(UC.instrucaoDescricao.get(UC.getCBR()));
        clock.setText(Integer.toString(Integer.parseInt(clock.getText()) + 1));
        
        //Highlight
        if(UC.getCBR().equals("11111111111111111111111111111111111")) {
            highlighter.removeAllHighlights();
            int p0 = 0; //começo do highlight
            int p1 = 0; //fim do highlight
            Scanner scan = new Scanner(Main.opcodeInMemory);
            while(scan.hasNextLine()) {
                String s = scan.nextLine();
                if(Main.assemblyOpcode.get(s).equals(IR.get())) {
                    p0 = Main.opcodeInMemory.indexOf(s); //Pega o primeiro que bater a string
                    String aux = Main.Code.substring(p0);
                    Scanner scan2 = new Scanner(aux);
                    String aux2 = scan2.nextLine();
                    p1 = p0 + aux2.length();
                }
            }
            try { highlighter.addHighlight(p0, p1, painter); } catch(Exception e){}
        }
        if (Integer.parseInt(UC.getCAR(),2) == 0) { //novo ciclo de busca
            highlighter.removeAllHighlights();
            //if(ultimaInstrucao) Step.setEnabled(false);
        }
        //System.out.println(Main.opcodeInMemory);
        
        if(UC.getOverflow()) {
            JOptionPane.showMessageDialog(null, "Overflow!", "Erro", JOptionPane.ERROR_MESSAGE);
            Step.setEnabled(false);
        }
    }//GEN-LAST:event_StepActionPerformed

    private void clockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
        Main.program();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarramentosPanel;
    private javax.swing.JScrollPane CodigoPane;
    private javax.swing.JTextArea CodigoText;
    private javax.swing.JScrollPane DescricaoPane;
    private javax.swing.JPanel FlagsPanel;
    private javax.swing.JPanel MicroprogramaPanel;
    private javax.swing.JPanel PrincipalPanel;
    private javax.swing.JPanel RegistradoresPanel;
    private javax.swing.JButton Step;
    private javax.swing.JTextField ax;
    private javax.swing.JTextField barramentoExterno;
    private javax.swing.JTextField barramentoInterno;
    private javax.swing.JTextField bx;
    private javax.swing.JTextField clock;
    private javax.swing.JTextField cx;
    private javax.swing.JTextArea descricao;
    private javax.swing.JTextField dx;
    private javax.swing.JTextField ir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mar;
    private javax.swing.JTextField mbr;
    private javax.swing.JTextField overflow;
    private javax.swing.JTextField palavra;
    private javax.swing.JTextField pc;
    private javax.swing.JTextField sinal;
    private javax.swing.JTextField zero;
    // End of variables declaration//GEN-END:variables
}
